<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitef6a4536c3dd28c829ad8ff1c2eb409e
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'Mai\\PerformanceImages\\Dependencies\\' => 35,
            'Mai\\PerformanceImages\\' => 22,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Mai\\PerformanceImages\\Dependencies\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/classes/Dependencies',
        ),
        'Mai\\PerformanceImages\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/classes',
        ),
    );

    public static $classMap = array (
        'ComposerAutoloaderInitef6a4536c3dd28c829ad8ff1c2eb409e' => __DIR__ . '/..' . '/composer/autoload_real.php',
        'Composer\\Autoload\\ClassLoader' => __DIR__ . '/..' . '/composer/ClassLoader.php',
        'Composer\\Autoload\\ComposerStaticInitef6a4536c3dd28c829ad8ff1c2eb409e' => __DIR__ . '/..' . '/composer/autoload_static.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'MaiPerformanceImages_WP_Async_Request' => __DIR__ . '/..' . '/deliciousbrains/wp-background-processing/classes/wp-async-request.php',
        'MaiPerformanceImages_WP_Background_Process' => __DIR__ . '/..' . '/deliciousbrains/wp-background-processing/classes/wp-background-process.php',
        'Mai\\PerformanceImages\\AbstractImages' => __DIR__ . '/../../..' . '/classes/class-abstract-images.php',
        'Mai\\PerformanceImages\\BackgroundProcess' => __DIR__ . '/../../..' . '/classes/class-background-process.php',
        'Mai\\PerformanceImages\\CLI' => __DIR__ . '/../../..' . '/classes/class-cli.php',
        'Mai\\PerformanceImages\\ImageCacheManager' => __DIR__ . '/../../..' . '/classes/class-image-cache-manager.php',
        'Mai\\PerformanceImages\\ImageLoading' => __DIR__ . '/../../..' . '/classes/class-image-loading.php',
        'Mai\\PerformanceImages\\ImageProcessor' => __DIR__ . '/../../..' . '/classes/class-image-processor.php',
        'Mai\\PerformanceImages\\Images' => __DIR__ . '/../../..' . '/classes/class-images.php',
        'Mai\\PerformanceImages\\Logger' => __DIR__ . '/../../..' . '/classes/class-logger.php',
        'Mai\\PerformanceImages\\MaiEngine' => __DIR__ . '/../../..' . '/classes/class-mai-engine.php',
        'Mai\\PerformanceImages\\Scheduler' => __DIR__ . '/../../..' . '/classes/class-scheduler.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitef6a4536c3dd28c829ad8ff1c2eb409e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitef6a4536c3dd28c829ad8ff1c2eb409e::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitef6a4536c3dd28c829ad8ff1c2eb409e::$classMap;

        }, null, ClassLoader::class);
    }
}
