<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));

return array(
    'Mai\\PerformanceImages\\Dependencies\\' => array($vendorDir . ''),
    'Mai\\PerformanceImages\\' => array($baseDir . '/classes'),
);
