<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitacfb92c4f968f557321ecf624876d544
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Mai\PerformanceImages\dependencies\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Mai\PerformanceImages\dependencies\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInitacfb92c4f968f557321ecf624876d544', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Mai\PerformanceImages\dependencies\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitacfb92c4f968f557321ecf624876d544', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Mai\PerformanceImages\dependencies\Composer\Autoload\ComposerStaticInitacfb92c4f968f557321ecf624876d544::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
