<?php

// autoload_static.php @generated by Composer

namespace Mai\PerformanceImages\dependencies\Composer\Autoload;

class ComposerStaticInitacfb92c4f968f557321ecf624876d544
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'Mai\\PerformanceImages\\dependencies\\' => 35,
            'Mai\\PerformanceImages\\' => 22,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Mai\\PerformanceImages\\dependencies\\' => 
        array (
            0 => __DIR__ . '/../..' . '/classes/dependencies',
        ),
        'Mai\\PerformanceImages\\' => 
        array (
            0 => __DIR__ . '/../..' . '/classes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'MaiPerformanceImages_WP_Async_Request' => __DIR__ . '/..' . '/deliciousbrains/wp-background-processing/classes/wp-async-request.php',
        'MaiPerformanceImages_WP_Background_Process' => __DIR__ . '/..' . '/deliciousbrains/wp-background-processing/classes/wp-background-process.php',
        'Mai\\PerformanceImages\\AbstractImages' => __DIR__ . '/../..' . '/classes/class-abstract-images.php',
        'Mai\\PerformanceImages\\BackgroundProcess' => __DIR__ . '/../..' . '/classes/class-background-process.php',
        'Mai\\PerformanceImages\\CLI' => __DIR__ . '/../..' . '/classes/class-cli.php',
        'Mai\\PerformanceImages\\DownloadManager' => __DIR__ . '/../..' . '/classes/class-download-manager.php',
        'Mai\\PerformanceImages\\ImageCacheManager' => __DIR__ . '/../..' . '/classes/class-image-cache-manager.php',
        'Mai\\PerformanceImages\\ImageLoading' => __DIR__ . '/../..' . '/classes/class-image-loading.php',
        'Mai\\PerformanceImages\\ImageProcessor' => __DIR__ . '/../..' . '/classes/class-image-processor.php',
        'Mai\\PerformanceImages\\Images' => __DIR__ . '/../..' . '/classes/class-images.php',
        'Mai\\PerformanceImages\\Logger' => __DIR__ . '/../..' . '/classes/class-logger.php',
        'Mai\\PerformanceImages\\MaiBlocks' => __DIR__ . '/../..' . '/classes/class-mai-blocks.php',
        'Mai\\PerformanceImages\\MaiEngine' => __DIR__ . '/../..' . '/classes/class-mai-engine.php',
        'Mai\\PerformanceImages\\Scheduler' => __DIR__ . '/../..' . '/classes/class-scheduler.php',
        'Mai\\PerformanceImages\\Updater' => __DIR__ . '/../..' . '/classes/class-updater.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitacfb92c4f968f557321ecf624876d544::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitacfb92c4f968f557321ecf624876d544::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitacfb92c4f968f557321ecf624876d544::$classMap;

        }, null, ClassLoader::class);
    }
}
