<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Mai\\PerformanceImages\\dependencies\\' => array($baseDir . '/classes/dependencies'),
    'Mai\\PerformanceImages\\' => array($baseDir . '/classes'),
);
